version: '3.8'
services:
  jenkins:
    image: jenkins:jcasc
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
  nginx:
    image: nginx-server:latest
    privileged: true
    user: root
    ports:
      - 5001:80
    container_name: nginx
