version: '3.8'
services:
  jenkins:
    image: jenkins:jcasc
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
  nginx:
    image: nginx-server:latest
    privileged: true
    user: root
    ports:
      - 5001:80
    container_name: nginx
#networks:
#  nama:
#    driver: bridge
    # volumes:
    #   - ~/jenkins:/var/jenkins_home
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - /usr/local/bin/docker:/usr/local/bin/docker
    #   - /usr/bin/docker:/usr/bin/docker